@host = http://localhost:5000
@postId = 0
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDAzIiwibmJmIjoxNzUwMjI1MTg1LCJleHAiOjE3NTAzMTE1ODUsImlhdCI6MTc1MDIyNTE4NX0.2-05nOgyijyAxrvkUfzc627JRrSMHjOCrvnia7Y4hTo
@searchTerm = "post"

### Login User Update

POST {{host}}/Auth/Login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "P@ssw0rd!"
}

### GET all posts

GET {{host}}/Post/Posts
Authorization: Bearer {{token}}

###

### GET posts by user (logged-in)

GET {{host}}/Post/UserPosts
Authorization: Bearer {{token}}

###

### Get Posts By Search Term

GET {{host}}/Post/PostsBySearch/{{searchTerm}}
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE a new post

PUT {{host}}/Post/UpdatePost
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "postTitle": "Judul Test Posting ke 2",
    "postContent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}

###

### UPDATE a post by ID

PUT {{host}}/Post/UpdatePost/{{postId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "postTitle": "Judul Postingan yang Diperbarui",
    "postContent": "Isi postingan setelah update."
}

###

### DELETE a post by ID

DELETE {{host}}/Post/DeletePost/{{postId}}
Authorization: Bearer {{token}}